export const topRated = {
  page: 1,
  results: [
    {
      poster_path:
        'https://festagent.com/system/tilda/tild3562-6362-4762-b036-653363663832__a01ccf32943f670ef632.jpg',
      adult: true,
      overview:
        'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
      release_date: 'mar 17 1948',
      genre_ids: [18, 20],
      id: 123412,
      original_title: 'The FiiiirstGodfather',
      original_language: 'english',
      title: 'The FiiiirstGodfathe',
      backdrop_path: 'string',
      popularity: 99,
      vote_count: 123,
      video: true,
      vote_average: 12,
      duration: '2h 55m',
      genre: 'Drama, Crime',
    },
    {
      poster_path:
        'https://festagent.com/system/tilda/tild3562-6362-4762-b036-653363663832__a01ccf32943f670ef632.jpg',
      adult: true,
      overview:
        'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
      release_date: 'mar 17 1948',
      genre_ids: [18, 20],
      id: 123412,
      original_title: 'The FiiiirstGodfather',
      original_language: 'english',
      title: 'The FiiiirstGodfathe',
      backdrop_path: 'string',
      popularity: 98,
      vote_count: 123,
      video: true,
      vote_average: 12,
      duration: '2h 55m',
      genre: 'Drama, Crime',
    },
    {
      poster_path:
        'https://festagent.com/system/tilda/tild3562-6362-4762-b036-653363663832__a01ccf32943f670ef632.jpg',
      adult: true,
      overview:
        'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
      release_date: 'mar 17 1948',
      genre_ids: [18, 20],
      id: 123412,
      original_title: 'The FiiiirstGodfather',
      original_language: 'english',
      title: 'The FiiiirstGodfathe',
      backdrop_path: 'string',
      popularity: 97,
      vote_count: 123,
      video: true,
      vote_average: 12,
      duration: '2h 55m',
      genre: 'Drama, Crime',
    },
    {
      poster_path:
        'https://festagent.com/system/tilda/tild3562-6362-4762-b036-653363663832__a01ccf32943f670ef632.jpg',
      adult: true,
      overview:
        'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
      release_date: 'mar 17 1948',
      genre_ids: [18, 20],
      id: 123412,
      original_title: 'The FiiiirstGodfather',
      original_language: 'english',
      title: 'The FiiiirstGodfathe',
      backdrop_path: 'string',
      popularity: 96,
      vote_count: 123,
      video: true,
      vote_average: 12,
      duration: '2h 55m',
      genre: 'Drama, Crime',
    },
    {
      poster_path:
        'https://festagent.com/system/tilda/tild3562-6362-4762-b036-653363663832__a01ccf32943f670ef632.jpg',
      adult: true,
      overview:
        'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
      release_date: 'mar 17 1948',
      genre_ids: [18, 20],
      id: 123412,
      original_title: 'The FiiiirstGodfather',
      original_language: 'english',
      title: 'The FiiiirstGodfathe',
      backdrop_path: 'string',
      popularity: 95,
      vote_count: 123,
      video: true,
      vote_average: 12,
      duration: '2h 55m',
      genre: 'Drama, Crime',
    },
    {
      poster_path:
        'https://festagent.com/system/tilda/tild3562-6362-4762-b036-653363663832__a01ccf32943f670ef632.jpg',
      adult: true,
      overview:
        'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
      release_date: 'mar 17 1948',
      genre_ids: [18, 20],
      id: 123412,
      original_title: 'The FiiiirstGodfather',
      original_language: 'english',
      title: 'The FiiiirstGodfathe',
      backdrop_path: 'string',
      popularity: 99,
      vote_count: 123,
      video: true,
      vote_average: 12,
      duration: '2h 55m',
      genre: 'Drama, Crime',
    },
  ],
  dates: {
    maximum: ' 12 klajs asd',
    minimum: '584a ',
  },
  total_pages: 98,
  total_results: 98,
};
